name: skript-gui
main: io.github.apickledwalrus.skriptgui.SkriptGUI
version: @version@
api-version: '1.21.1'
folia-supported: true
authors: [APickledWalrus]
description: Enables the easy creation of advanced and organized GUIs with Skript.
website: https://github.com/APickledWalrus/skript-gui
dependencies:
  server:
    Skript:
      load: BEFORE
      required: false
